# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d7b960ebc4a4cb9aba40862018a45d5433c599e2ab2ab59e6d7886b47afc911592f61b44ceb16d31ff6b5571ae1b967bf287fe535dfeee5a76a1626ac37ed2

test:
  secret_key_base: 3e7c685f823b7376b70c27c8a5e750d904a6339a142dc4a89f50d419bf04e9a670841d3048db1a46aee1081851148a4d0f698ba64e6c4b54808ffdaf855e2d77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
